-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 21:45:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lerarquivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lerarquivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lerarquivo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lerarquivo` ;

-- -----------------------------------------------------
-- Table `lerarquivo`.`reg30`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lerarquivo`.`reg30` (
  `id_linha_30` INT(11) NOT NULL AUTO_INCREMENT,
  `dtEmissao` VARCHAR(15) NULL DEFAULT NULL,
  `redeCard` VARCHAR(250) NULL DEFAULT NULL,
  `ext_mov_finan` VARCHAR(50) NULL DEFAULT NULL,
  `nom_fant` VARCHAR(250) NULL DEFAULT NULL,
  `sequ_mov` INT(11) NULL DEFAULT NULL,
  `cod_pv_fan` INT(11) NULL DEFAULT NULL,
  `tp_reproc` VARCHAR(50) NULL DEFAULT NULL,
  `version` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id_linha_30`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lerarquivo`.`reg32`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lerarquivo`.`reg32` (
  `id_linha_32` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_pv_fan` VARCHAR(150) NULL DEFAULT NULL,
  `nom_fan` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_linha_32`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lerarquivo`.`reg34`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lerarquivo`.`reg34` (
  `id_linha_34` INT(11) NOT NULL AUTO_INCREMENT,
  `num_pv_cen` INT(11) NULL DEFAULT NULL,
  `num_doc` INT(11) NULL DEFAULT NULL,
  `dt_lanc` VARCHAR(15) NULL DEFAULT NULL,
  `val_lanc` DECIMAL(13,2) NULL DEFAULT NULL,
  `c_cred` VARCHAR(50) NULL DEFAULT NULL,
  `num_banc` INT(11) NULL DEFAULT NULL,
  `num_agen` INT(11) NULL DEFAULT NULL,
  `num_cont_corr` INT(11) NULL DEFAULT NULL,
  `dt_mov` VARCHAR(15) NOT NULL,
  `num_rv` INT(11) NULL DEFAULT NULL,
  `dt_rv` VARCHAR(15) NULL DEFAULT NULL,
  `bandeira` INT(11) NULL DEFAULT NULL,
  `tp_trans` INT(11) NULL DEFAULT NULL,
  `val_bruto_rv` DECIMAL(13,2) NULL DEFAULT NULL,
  `val_taxa_desc` DECIMAL(13,2) NULL DEFAULT NULL,
  `num_parcelas` VARCHAR(150) NULL DEFAULT NULL,
  `status_cred` VARCHAR(150) NULL DEFAULT NULL,
  `num_pv_original` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_linha_34`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
